---
- hosts: appservers
  remote_user: hackday
  tasks:
    - name: Create directory
      file: path=/home/hackday/log_collection state=directory
    - name: Clear logs directory
      file:
        state: absent
        path: /home/hackday/log_collection/logs
    - name: Create logs directory
      file: path=/home/hackday/log_collection/logs state=directory
    - name: Copy script
      copy: src={{path}}/get_log.py dest=/home/hackday/log_collection/get_log.py
    - name: Copy service unit
      copy: src={{path}}/ansible-files/get_log.service dest=/etc/systemd/system
      become: yes
      become_method: su
    - name: Stop script
      systemd:
        name: get_log
        state: stopped
      become: yes
      become_method: su
    - name: Reload server
      systemd: daemon_reload=yes
      become: yes
      become_method: su
    - name: Start script
      systemd:
        name: get_log
        state: started
      become: yes
      become_method: su
