---
- hosts: appservers
  remote_user: hackday
  tasks:
    - name: create directory
      file: path=/home/hackday/scripts state=directory
    - name: copy script
      copy: src={{path}}/get_log.py dest=/home/hackday/scripts/get_log.py
    - name: run script
      command: nohup python /home/hackday/scripts/get_log.py &
