---
- hosts: appservers
  remote_user: hackday
  tasks:
    - name: copy script
      copy: src={{path}}/monitoring/get_log.py dest=/home/hackday/scripts/get_log.py
    - name: run script
      command: python /home/hackday/scripts/get_log.py
