---
- hosts: appservers
  remote_user: hackday
  tasks:
    - name: create directory
      file: path=/home/hackday/scripts state=directory
    - name: copy script
      copy: src={{path}}/get_log.py dest=/home/hackday/scripts/get_log.py
    #- name: run script
    #  command: nohup /usr/bin/python /home/hackday/scripts/get_log.py &
    - name: copy service unit
      copy: src={{path}}/ansible-files/get_log.service dest=/etc/systemd/system
      become: yes
      become_method: su
    - name: stop script
      systemd:
        name: get_log
        state: stopped
      become: yes
      become_method: su
    - name: reload server
      systemd: daemon_reload=yes
      become: yes
      become_method: su
    - name: start script
      systemd:
        name: get_log
        state: started
      become: yes
      become_method: su
