---
- hosts: localhost
  become: yes
  tasks:
    - name: start docker service
      systemd:
        name: docker
        state: started
      become: yes
      become_method: su
    - name: kill elk container
      docker_service:
        project_src: ../elk
        state: absent
      become: yes
      become_method: su
    - name: start elk container
      docker_service:
        project_src: ../elk
        build: yes
      become: yes
      become_method: su 
    - name: start logging elk
      shell: 'docker-compose logs -t -f >> var/log/elk.log&'
      args:
       chdir: ../elk 

