---
- hosts: localhost
  become: yes
  tasks:
    - name: start docker service
      systemd:
        name: docker
        state: started
      become: yes
      become_method: su
    - name: kill elk container
      docker_service:
        project_src: ../elk
        state: absent
      become: yes
      become_method: su
    - name: start elk container
      docker_service:
        project_src: ../elk
        build: yes
      become: yes
      become_method: su 
